cmake_minimum_required(VERSION 3.21)

if(DEFINED CASE)
    set(CMAKE_SOURCE_DIR "${TEXTURE_LOADER_SOURCE_DIR}")
    set(CMAKE_CURRENT_SOURCE_DIR "${TEXTURE_LOADER_SOURCE_DIR}")
    set(_toolchain "${CMAKE_CURRENT_SOURCE_DIR}/external/test-vcpkg/scripts/buildsystems/vcpkg.cmake")
    set(CMAKE_TOOLCHAIN_FILE "${_toolchain}")
    set(VCPKG_MANIFEST_FEATURES "oiio;tests;caller-feature" CACHE STRING "")
    set(USE_OIIO OFF)
    set(BUILD_TESTS OFF)
    set(_expected "caller-feature")

    if(CASE STREQUAL "oiio")
        set(USE_OIIO ON)
        list(APPEND _expected oiio)
    elseif(CASE STREQUAL "tests")
        set(BUILD_TESTS ON)
        list(APPEND _expected tests)
    elseif(CASE STREQUAL "both")
        set(USE_OIIO ON)
        set(BUILD_TESTS ON)
        list(APPEND _expected oiio tests)
    elseif(CASE STREQUAL "invalid-root")
        unset(CMAKE_TOOLCHAIN_FILE)
        set(ENV{VCPKG_ROOT} "${CMAKE_CURRENT_BINARY_DIR}/not-a-vcpkg-installation")
    elseif(CASE STREQUAL "other-toolchain")
        set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/other-toolchain.cmake")
    elseif(CASE STREQUAL "subdirectory")
        set(CMAKE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/parent")
    elseif(NOT CASE STREQUAL "neither")
        message(FATAL_ERROR "Unknown case: ${CASE}")
    endif()

    include("${TEXTURE_LOADER_SOURCE_DIR}/cmake/VcpkgBootstrap.cmake")
    if(NOT VCPKG_MANIFEST_FEATURES STREQUAL _expected)
        message(FATAL_ERROR "Features: expected '${_expected}', got '${VCPKG_MANIFEST_FEATURES}'")
    endif()
    if(NOT CMAKE_TOOLCHAIN_FILE STREQUAL _toolchain)
        message(FATAL_ERROR "The explicit toolchain was replaced")
    endif()
    return()
endif()

foreach(_case neither oiio tests both invalid-root other-toolchain subdirectory)
    execute_process(
        COMMAND "${CMAKE_COMMAND}"
            "-DTEXTURE_LOADER_SOURCE_DIR=${TEXTURE_LOADER_SOURCE_DIR}"
            "-DCASE=${_case}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE _result
        OUTPUT_VARIABLE _output
        ERROR_VARIABLE _error)
    set(_expected_error "")
    if(_case STREQUAL "invalid-root")
        set(_expected_error "VCPKG_ROOT does not contain")
    elseif(_case STREQUAL "other-toolchain")
        set(_expected_error "USE_VCPKG requires the vcpkg toolchain")
    elseif(_case STREQUAL "subdirectory")
        set(_expected_error "Enable vcpkg in the parent project")
    endif()
    if(_expected_error)
        if(_result EQUAL 0 OR NOT _error MATCHES "${_expected_error}")
            message(FATAL_ERROR "${_case}: expected '${_expected_error}', got:\n${_output}\n${_error}")
        endif()
    elseif(NOT _result EQUAL 0)
        message(FATAL_ERROR "${_case} failed:\n${_output}\n${_error}")
    endif()
endforeach()
message(STATUS "Passed all 7 vcpkg configuration cases")
